#!/usr/bin/env node
/**
 * Compatibility tests for the systems-playground engine.
 *
 * fixtures.json was generated by running the original Python package
 * (https://github.com/lethain/systems) over its examples/ corpus plus
 * targeted edge cases (capacity clamps, conversion flooring, reversed
 * flow ordering, conflicting declarations, …). Each fixture is either
 * the expected per-round table or the Python exception type for models
 * the original rejects.
 *
 * The playground language requires stocks to be declared up front, so the
 * sources below are the lethain/systems models rewritten in that form —
 * declarations first (in the original's stock order, so columns line up),
 * then the original flow lines. The engine semantics under test are
 * unchanged: the expected tables come straight from the Python original.
 *
 * Usage: node tools/systems-playground/tests/run-tests.mjs
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyze, hasErrors } from '../lang.js';
import { run } from '../engine.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(join(here, 'fixtures.json'), 'utf8'));

const SOURCES = {
  'extended_syntax.txt': `[Candidate]
Recruiter(5)
EngRecruiter(1, Recruiter)
MgrRecruiter(1, Recruiter)
Hire
Departure
[Departed]

Recruiter > EngRecruiter @ Rate(Recruiter * 2)
Recruiter > MgrRecruiter @ Rate(Recruiter * 1)

[Candidate] > Hire @ Recruiter * 3

Hire > Departure @ Leak(0.1)
Departure > [Departed] @ 1.0
`,
  'fake_flow.txt': `b
d
e
b > d @ Invalid(5)
d > e @ Fake(5)
`,
  'hiring.txt': `[Candidates]
PhoneScreens
Onsites
Offers
Hires
Employees(5)
Departures
[Departed]

[Candidates] > PhoneScreens @ 25
PhoneScreens > Onsites      @ 0.5
Onsites      > Offers       @ 0.5
Offers       > Hires        @ 0.5
Hires        > Employees    @ 1.0
Employees    > Departures   @ Leak(0.1)
Departures   > [Departed]   @ 1.0
`,
  'illegal_maximum.txt': `# "illegal" initial above the maximum — the original runs it anyway
a(5, 5)
b
c(5, 3)
d
a > b @ 1
a > c @ 1
c > d @ 1
`,
  'invalid_flow.txt': `a
b
c
a > b @ 0..2
b > c @ .2
`,
  'links.txt': `[PossibleRecruiters]
Recruiters(10, 15)
[Candidates]
PhoneScreens
Onsites
Offers
Hires
Employees
Departures
[Departed]

[PossibleRecruiters] > Recruiters @ 1

[Candidates] > PhoneScreens @ Recruiters * 3
PhoneScreens > Onsites      @ 0.5
Onsites      > Offers       @ 0.5
Offers       > Hires        @ 0.5
Hires        > Employees    @ 1.0
Employees    > Departures   @ Leak(0.1)
Departures   > [Departed]   @ 1.0
`,
  'maximums.txt': `[a]
b(0, 5)
c(0, 10)
[a] > b @ 10
b > c @ 5
`,
  'no_delim.txt': `[a]
b
[a] < b @ 25
[a] > b * 0.25
`,
  'projects.txt': `[Hires]
Developers
[Ideas]
Projects
Started
Finished
[Hires] > Developers @ 1
[Ideas] > Projects   @ Developers / (Projects+1)
Projects > Started   @ Developers - (Started+1)
Started > Finished   @ Developers
`,
  readme_hiring: `[Candidates]
PhoneScreens
Onsites
Offers
Hires
Employees
Departures
[Departed]
Recruiters(3)

[Candidates] > PhoneScreens @ Recruiters * 3
PhoneScreens > Onsites @ 0.5
Onsites > Offers @ 0.5
Offers > Hires @ 0.5
Hires > Employees @ 1.0
Employees > Departures @ Leak(0.1)
Departures > [Departed] @ 1.0
`,
  initial_refs: `Managers(2)
Engineers(Managers * 4, Managers * 8)
[Candidates]
[Candidates] > Engineers @ 1
[Candidates] > Managers @ 1
`,
  rate_clamp: 'a(3)\nb\na > b @ 5\n',
  max_capacity: '[a]\nb(0, 7)\n[a] > b @ 3\n',
  conversion_capacity: 'a(10)\nb(0, 4)\na > b @ 0.5\n',
  leak_capacity: 'a(100)\nb(0, 30)\na > b @ Leak(0.5)\n',
  negative_rate: 'a(5)\nb\na > b @ 0 - 2\n',
  explicit_rate_decimal: 'a(10)\nb\na > b @ Rate(0.5)\n',
  conversion_floor: 'a(7)\nb\na > b @ 0.5\n',
  chain_order: 'a(10)\nb\nc\na > b @ 2\nb > c @ 2\n',
  multi_outflow: 'a(10)\nb\nc\na > b @ 6\na > c @ 6\n',
  conversion_overdrain: 'a(2)\nb(0, 100)\na > b @ 0.5\n',
  conversion_one: 'a(10)\nb\nc\na > b @ 1.0\nb > c @ 0.5\n',
  leak_then_refill: '[src]\na\nb\n[src] > a @ 3\na > b @ Leak(0.5)\n',
  max_formula: 'Managers(2)\n[Candidates]\nEngineers(0, Managers * 3)\n[Candidates] > Engineers @ 2\n',
  rate_formula_div: '[Hires]\nDevelopers\n[Ideas]\nProjects\n[Hires] > Developers @ 1\n[Ideas] > Projects @ Developers / (Projects + 1)\n',
};

const decode = (v) => (v === 'inf' ? Infinity : v === 'nan' ? NaN : v);
const close = (a, b) => {
  if (a === b) return true;
  if (Number.isNaN(a) && Number.isNaN(b)) return true;
  return Math.abs(a - b) <= 1e-9 * Math.max(1, Math.abs(a), Math.abs(b));
};

let pass = 0;
let fail = 0;
const failures = [];

for (const fixture of fixtures) {
  const [key, roundsStr] = fixture.name.split('@');
  const source = SOURCES[key];
  if (!source) {
    failures.push(`${fixture.name}: no source registered in run-tests.mjs`);
    fail++;
    continue;
  }
  const rounds = parseInt(roundsStr, 10);
  const analysis = analyze(source);

  if (fixture.error) {
    // The original Python implementation rejects this model; the analyzer
    // must produce at least one error diagnostic.
    if (hasErrors(analysis)) {
      pass++;
    } else {
      fail++;
      failures.push(`${fixture.name}: expected an error (${fixture.error}) but analysis was clean`);
    }
    continue;
  }

  if (hasErrors(analysis)) {
    fail++;
    const msgs = analysis.diagnostics.filter((d) => d.severity === 'error').map((d) => d.message);
    failures.push(`${fixture.name}: unexpected analyzer errors: ${msgs.join(' | ')}`);
    continue;
  }

  const result = run(analysis, { rounds });
  const gotCols = result.columns.filter((c) => c.kind === 'stock').map((c) => c.name);
  if (JSON.stringify(gotCols) !== JSON.stringify(fixture.columns)) {
    fail++;
    failures.push(`${fixture.name}: columns ${JSON.stringify(gotCols)} != ${JSON.stringify(fixture.columns)}`);
    continue;
  }

  let ok = true;
  if (result.rows.length !== fixture.rows.length) {
    ok = false;
    failures.push(`${fixture.name}: ${result.rows.length} rows != ${fixture.rows.length}`);
  } else {
    outer: for (let r = 0; r < fixture.rows.length; r++) {
      for (let c = 0; c < fixture.columns.length; c++) {
        const want = decode(fixture.rows[r][c]);
        const got = result.rows[r][c];
        if (!close(got, want)) {
          ok = false;
          failures.push(`${fixture.name}: row ${r}, ${fixture.columns[c]}: got ${got}, want ${want}`);
          break outer;
        }
      }
    }
  }
  if (ok) pass++; else fail++;
}

// --- extension smoke tests (our own semantics, locked in as regression) ---

function expect(name, cond, detail = '') {
  if (cond) { pass++; } else { fail++; failures.push(`${name}: ${detail}`); }
}

{
  // Auxiliaries + builtins + determinism.
  const src = `[Pool]
Hires
Staff(10)
Departures

[Pool] > Hires @ HiringRate
Hires > Staff @ 1.0
Staff > Departures @ Leak(0.1)

HiringRate = MAX(2, ROUND(Staff * 0.2))
Pressure = IF Staff > 20 THEN 1 ELSE 0
`;
  const a = analyze(src);
  expect('ext/aux analyze', !hasErrors(a),
    a.diagnostics.filter((d) => d.severity === 'error').map((d) => d.message).join(' | '));
  if (!hasErrors(a)) {
    const r1 = run(a, { rounds: 12, seed: 7 });
    const r2 = run(a, { rounds: 12, seed: 7 });
    expect('ext/aux deterministic', JSON.stringify(r1.rows) === JSON.stringify(r2.rows));
    const cols = r1.columns.map((c) => c.name);
    expect('ext/aux columns', cols.includes('HiringRate') && cols.includes('Pressure'),
      JSON.stringify(cols));
  }
}

{
  // Declarations: descriptions and visibility flags.
  const src = `[Pool]
A(1) "stock A, hidden from the chart" visible: false
B "stock B"

[Pool] > A @ 2
A > B @ Leak(0.5)
`;
  const a = analyze(src);
  expect('decl/attrs analyze', !hasErrors(a),
    a.diagnostics.filter((d) => d.severity === 'error').map((d) => d.message).join(' | '));
  expect('decl/description', a.stocks.get('A')?.description === 'stock A, hidden from the chart'
    && a.stocks.get('B')?.description === 'stock B');
  expect('decl/visible flag', a.stocks.get('A')?.visible === false && a.stocks.get('B')?.visible === null);
  const r = run(a, { rounds: 5 });
  const byName = Object.fromEntries(r.columns.map((c) => [c.name, c]));
  expect('decl/column visibility', byName.A.visible === false && byName.B.visible === true,
    JSON.stringify(r.columns));
  expect('decl/hidden stays in table', r.columns.some((c) => c.name === 'A'));
}

{
  // Seeded randomness: same seed reproduces, different seed differs.
  const src = '[Pool]\nArrivals\n[Pool] > Arrivals @ POISSON(4)\n';
  const a = analyze(src);
  expect('ext/random analyze', !hasErrors(a));
  const r1 = run(a, { rounds: 20, seed: 1 });
  const r2 = run(a, { rounds: 20, seed: 1 });
  const r3 = run(a, { rounds: 20, seed: 2 });
  expect('ext/random same seed', JSON.stringify(r1.rows) === JSON.stringify(r2.rows));
  expect('ext/random diff seed', JSON.stringify(r1.rows) !== JSON.stringify(r3.rows));
}

{
  // Test-input builtins.
  const src = '[Pool]\nOutput\n[Pool] > Output @ STEP(5, 3) + PULSE(10, 2, 4)\n';
  const a = analyze(src);
  expect('ext/test-inputs analyze', !hasErrors(a));
  const r = run(a, { rounds: 8 });
  const out = r.rows.map((row) => row[0]);
  // Flows of round t (TIME()=t) land in row t+1. STEP(5,3) adds 5 from
  // round 3 on; PULSE(10,2,4) adds 10 at rounds 2 and 6.
  expect('ext/test-inputs values', JSON.stringify(out) === JSON.stringify([0, 0, 0, 10, 15, 20, 25, 40, 45]),
    JSON.stringify(out));
}

{
  // Domain diagnostics.
  const cases = [
    ['undefined ref', '[a]\nb\n[a] > b @ Recruiters * 2\n', 'undefined'],
    ['undeclared flow stock', '[a]\n[a] > b @ 1\n', 'undeclared'],
    ['use before declaration', '[a] > b @ 1\n[a]\nb\n', 'before its declaration'],
    ['inline decl in flow', '[a]\nb\n[a] > b(5) @ 1\n', 'up front'],
    ['leak from infinite', '[a]\nb\n[a] > b @ Leak(0.5)\n', "can't drain"],
    ['aux cycle', 'x = y + 1\ny = x + 1\n', 'cycle'],
    ['self-referencing initial', 'a(a)\nb\na > b @ 1\n', 'cycle'],
    ['unknown fn', '[a]\nb\n[a] > b @ FOO(1)\n', 'Unknown function'],
    ['arity', '[a]\nb\n[a] > b @ MIN(1)\n', 'argument'],
    ['declared twice', 'a(1)\na(2)\nb\na > b @ 1\n', 'declared twice'],
    ['bracket mismatch', 'a\nb\n[a] > b @ 1\n', "isn't an infinite stock"],
    ['flow without rate', 'a\nb\na > b\n', "'@'"],
    ['infinite with params', 'a\nb\na > b @ 1\nc = a\n[c]\n', 'auxiliary'],
  ];
  for (const [name, src, needle] of cases) {
    const a = analyze(src);
    const errs = a.diagnostics.filter((d) => d.severity === 'error');
    expect(`diag/${name}`, errs.some((e) => e.message.toLowerCase().includes(needle.toLowerCase())),
      `got: ${errs.map((e) => e.message).join(' | ') || '(no errors)'}`);
  }
}

console.log(`${pass} passed, ${fail} failed`);
if (failures.length) {
  console.log('\nFailures:');
  for (const f of failures) console.log('  ✗ ' + f);
  process.exit(1);
}
