#!/usr/bin/env node
/**
 * Compatibility tests for the systems-playground engine.
 *
 * fixtures.json was generated by running the original Python package
 * (https://github.com/lethain/systems) over its examples/ corpus plus
 * targeted edge cases (capacity clamps, conversion flooring, reversed
 * flow ordering, conflicting declarations, …). Each fixture is either
 * the expected per-round table or the Python exception type for models
 * the original rejects.
 *
 * The fixture sources live in lethain/systems' examples/ directory and in
 * the inline `SOURCES` map below.
 *
 * Usage: node tools/systems-playground/tests/run-tests.mjs
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyze, hasErrors } from '../lang.js';
import { run } from '../engine.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(join(here, 'fixtures.json'), 'utf8'));

// Model sources, keyed by fixture name prefix. The *.txt entries are
// verbatim copies of lethain/systems examples/ (MIT licensed).
const SOURCES = {
  'extended_syntax.txt': `[Candidate]
Recruiter(5)
EngRecruiter(1, Recruiter)
MgrRecruiter(1, Recruiter)

Recruiter > EngRecruiter @ Rate(Recruiter * 2)
Recruiter > MgrRecruiter @ Rate(Recruiter * 1)

[Candidate] > Hire @ Recruiter * 3

Hire > Departure @ Leak(0.1)
Departure > [Departed] @ 1.0
`,
  'fake_flow.txt': `b > d @ Invalid(5)
d > e @ Fake(5)
`,
  'hiring.txt': `# wrap with [] to indicate an infinite stock that
# isn't included in each table
# integers are implicitly steady rates
[Candidates] > PhoneScreens @ 25

# floats are implicitly conversions that convert the
# source stock into the destination stock at a discount
# e.g. a source at 10 with a 0.5 conversion would empty
# itself and add 5 units to the destination
PhoneScreens > Onsites      @ 0.5
Onsites      > Offers       @ 0.5
Offers       > Hires        @ 0.5
Hires        > Employees(5) @ 1.0

# specify leak to avoid a destructive conversion
Employees    > Departures   @ Leak(0.1)
Departures   > [Departed]   @ 1.0
`,
  'illegal_maximum.txt': `# illegal maximum on line 4
a > b @ 1
a(5, 5) > c @ 1
c(5, 3) > d @ 1
`,
  'invalid_flow.txt': `a > b @ 0..2
b > c @ .2
`,
  'links.txt': `[PossibleRecruiters] > Recruiters(10, 15) @ 1

[Candidates] > PhoneScreens @ Recruiters * 3
PhoneScreens > Onsites      @ 0.5
Onsites      > Offers       @ 0.5
Offers       > Hires        @ 0.5
Hires        > Employees    @ 1.0
Employees    > Departures   @ Leak(0.1)
Departures   > [Departed]   @ 1.0
`,
  'maximums.txt': `[a] > b @ 10
b(0, 5) > c(0, 10) @ 5
`,
  'no_delim.txt': `[a] < b @ 25
[a] > b * 0.25
`,
  'projects.txt': `[Hires] > Developers @ 1
[Ideas] > Projects   @ Developers / (Projects+1)
Projects > Started   @ Developers - (Started+1)
Started > Finished   @ Developers
`,
  readme_hiring: `[Candidates] > PhoneScreens @ Recruiters * 3
PhoneScreens > Onsites @ 0.5
Onsites > Offers @ 0.5
Offers > Hires @ 0.5
Hires > Employees @ 1.0
Employees > Departures @ Leak(0.1)
Departures > [Departed] @ 1.0
Recruiters(3)
`,
  initial_refs: `Managers(2)
Engineers(Managers * 4, Managers * 8)
[Candidates] > Engineers @ 1
[Candidates] > Managers @ 1
`,
  rate_clamp: 'a(3) > b @ 5\n',
  max_capacity: '[a] > b(0, 7) @ 3\n',
  conversion_capacity: 'a(10) > b(0, 4) @ 0.5\n',
  leak_capacity: 'a(100) > b(0, 30) @ Leak(0.5)\n',
  negative_rate: 'a(5) > b @ 0 - 2\n',
  explicit_rate_decimal: 'a(10) > b @ Rate(0.5)\n',
  conversion_floor: 'a(7) > b @ 0.5\n',
  chain_order: 'a(10) > b @ 2\nb > c @ 2\n',
  multi_outflow: 'a(10) > b @ 6\na > c @ 6\n',
  conversion_overdrain: 'a(2) > b(0, 100) @ 0.5\n',
  conversion_one: 'a(10) > b @ 1.0\nb > c @ 0.5\n',
  leak_then_refill: '[src] > a @ 3\na > b @ Leak(0.5)\n',
  max_formula: 'Managers(2)\n[Candidates] > Engineers(0, Managers * 3) @ 2\n',
  rate_formula_div: '[Hires] > Developers @ 1\n[Ideas] > Projects @ Developers / (Projects + 1)\n',
};

const decode = (v) => (v === 'inf' ? Infinity : v === 'nan' ? NaN : v);
const close = (a, b) => {
  if (a === b) return true;
  if (Number.isNaN(a) && Number.isNaN(b)) return true;
  return Math.abs(a - b) <= 1e-9 * Math.max(1, Math.abs(a), Math.abs(b));
};

let pass = 0;
let fail = 0;
const failures = [];

for (const fixture of fixtures) {
  const [key, roundsStr] = fixture.name.split('@');
  const source = SOURCES[key];
  if (!source) {
    failures.push(`${fixture.name}: no source registered in run-tests.mjs`);
    fail++;
    continue;
  }
  const rounds = parseInt(roundsStr, 10);
  const analysis = analyze(source);

  if (fixture.error) {
    // The original Python implementation rejects this model; the analyzer
    // must produce at least one error diagnostic.
    if (hasErrors(analysis)) {
      pass++;
    } else {
      fail++;
      failures.push(`${fixture.name}: expected an error (${fixture.error}) but analysis was clean`);
    }
    continue;
  }

  if (hasErrors(analysis)) {
    fail++;
    const msgs = analysis.diagnostics.filter((d) => d.severity === 'error').map((d) => d.message);
    failures.push(`${fixture.name}: unexpected analyzer errors: ${msgs.join(' | ')}`);
    continue;
  }

  const result = run(analysis, { rounds });
  const gotCols = result.columns.filter((c) => c.kind === 'stock').map((c) => c.name);
  if (JSON.stringify(gotCols) !== JSON.stringify(fixture.columns)) {
    fail++;
    failures.push(`${fixture.name}: columns ${JSON.stringify(gotCols)} != ${JSON.stringify(fixture.columns)}`);
    continue;
  }

  let ok = true;
  if (result.rows.length !== fixture.rows.length) {
    ok = false;
    failures.push(`${fixture.name}: ${result.rows.length} rows != ${fixture.rows.length}`);
  } else {
    outer: for (let r = 0; r < fixture.rows.length; r++) {
      for (let c = 0; c < fixture.columns.length; c++) {
        const want = decode(fixture.rows[r][c]);
        const got = result.rows[r][c];
        if (!close(got, want)) {
          ok = false;
          failures.push(`${fixture.name}: row ${r}, ${fixture.columns[c]}: got ${got}, want ${want}`);
          break outer;
        }
      }
    }
  }
  if (ok) pass++; else fail++;
}

// --- extension smoke tests (our own semantics, locked in as regression) ---

function expect(name, cond, detail = '') {
  if (cond) { pass++; } else { fail++; failures.push(`${name}: ${detail}`); }
}

{
  // Auxiliaries + builtins + determinism.
  const src = `[Pool] > Hires @ HiringRate
Staff(10)
Hires > Staff @ 1.0
Staff > Departures @ Leak(0.1)
HiringRate = MAX(2, ROUND(Staff * 0.2))
Pressure = IF Staff > 20 THEN 1 ELSE 0
`;
  const a = analyze(src);
  expect('ext/aux analyze', !hasErrors(a),
    a.diagnostics.filter((d) => d.severity === 'error').map((d) => d.message).join(' | '));
  if (!hasErrors(a)) {
    const r1 = run(a, { rounds: 12, seed: 7 });
    const r2 = run(a, { rounds: 12, seed: 7 });
    expect('ext/aux deterministic', JSON.stringify(r1.rows) === JSON.stringify(r2.rows));
    const cols = r1.columns.map((c) => c.name);
    expect('ext/aux columns', cols.includes('HiringRate') && cols.includes('Pressure'),
      JSON.stringify(cols));
  }
}

{
  // Seeded randomness: same seed reproduces, different seed differs.
  const src = '[Pool] > Arrivals @ POISSON(4)\n';
  const a = analyze(src);
  expect('ext/random analyze', !hasErrors(a));
  const r1 = run(a, { rounds: 20, seed: 1 });
  const r2 = run(a, { rounds: 20, seed: 1 });
  const r3 = run(a, { rounds: 20, seed: 2 });
  expect('ext/random same seed', JSON.stringify(r1.rows) === JSON.stringify(r2.rows));
  expect('ext/random diff seed', JSON.stringify(r1.rows) !== JSON.stringify(r3.rows));
}

{
  // Test-input builtins.
  const src = '[Pool] > Output @ STEP(5, 3) + PULSE(10, 2, 4)\n';
  const a = analyze(src);
  expect('ext/test-inputs analyze', !hasErrors(a));
  const r = run(a, { rounds: 8 });
  const out = r.rows.map((row) => row[0]);
  // Flows of round t (TIME()=t) land in row t+1. STEP(5,3) adds 5 from
  // round 3 on; PULSE(10,2,4) adds 10 at rounds 2 and 6.
  expect('ext/test-inputs values', JSON.stringify(out) === JSON.stringify([0, 0, 0, 10, 15, 20, 25, 40, 45]),
    JSON.stringify(out));
}

{
  // Domain diagnostics.
  const cases = [
    ['undefined ref', '[a] > b @ Recruiters * 2\n', 'undefined'],
    ['leak from infinite', '[a] > b @ Leak(0.5)\n', "can't drain"],
    ['aux cycle', 'x = y + 1\ny = x + 1\n', 'cycle'],
    ['initial cycle', 'a(b)\nb(a)\na > b @ 1\n', 'cycle'],
    ['unknown fn', '[a] > b @ FOO(1)\n', 'Unknown function'],
    ['arity', '[a] > b @ MIN(1)\n', 'argument'],
    ['double init', 'a(1) > b @ 1\na(2) > c @ 1\n', 'initial value'],
  ];
  for (const [name, src, needle] of cases) {
    const a = analyze(src);
    const errs = a.diagnostics.filter((d) => d.severity === 'error');
    expect(`diag/${name}`, errs.some((e) => e.message.toLowerCase().includes(needle.toLowerCase())),
      `got: ${errs.map((e) => e.message).join(' | ') || '(no errors)'}`);
  }
}

console.log(`${pass} passed, ${fail} failed`);
if (failures.length) {
  console.log('\nFailures:');
  for (const f of failures) console.log('  ✗ ' + f);
  process.exit(1);
}
